### ISSUE TITLE
News heat map

### ISSUE THREAD

**Issue by brettgolden** [vinodnayal/finance#11]
![stocks](https://cloud.githubusercontent.com/assets/15707387/11017155/8a17eb1a-8564-11e5-8237-97f9ba558c29.png)

**Comment by vinodnayal** [comment]
what is problem if they are 20 it is very easy for me but what is issue with 20 ?

**Comment by brettgolden** [comment]
I don't want to overwhelm them with too much actionable data

**Comment by vinodnayal** [comment]
there were 80 symbols and now 20 check it now
http://199.30.94.116:8000/news
