### ISSUE TITLE
MACD calculation not correct

### ISSUE THREAD

**Issue by brettgolden** [vinodnayal/finance#24]
![macd](https://cloud.githubusercontent.com/assets/15707387/11018226/9a6890d6-858d-11e5-943b-188e42bd1e3e.png)

**Comment by brettgolden** [comment]
momentum should be less lumpy not as ridged and volatile

**Comment by vinodnayal** [comment]
i am using talib and not sure what ichart is using . i can not change calculations . it is waht talib provides me

**Comment by vinodnayal** [comment]
om we should use macd everywhere don't use mom . i will remove it 
i have made changes for this now
